apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: game-fleet-system

resources:
  - ../config/crds/gameserverfleets.yaml
  - ../config/crds/autoscalerpolicies.yaml
  - ../config/crds/gameserverallocations.yaml
  - ../config/rbac/role.yaml
  - ../config/rbac/role_binding.yaml
  - controller.yaml
  - apiserver.yaml

images:
  - name: registry.cn-beijing.aliyuncs.com/noneedtostudy/game-fleet-director-controller
    newTag: v0.1.0
  - name: registry.cn-beijing.aliyuncs.com/noneedtostudy/game-fleet-director-apiserver
    newTag: v0.1.0
